#!/usr/bin/env bash
# bootstrap.sh — generate a NATS deployment for the Locutorium.
#
#   bootstrap.sh <endpoint> [<endpoint> ...]
#
# Writes to $LOC_HOME (default ~/.locutorium):
#   config             flat key=value (provider, url, window)
#   endpoints          the deployment's registry, one name per line
#   creds/<name>       one credential file per endpoint + admin + watch (0600)
#   nats-server.conf   loopback listener, jetstream, per-user permissions
#
# Idempotence: refuses to overwrite an existing deployment unless --force.
# The server config it writes must then be installed where your service
# manager expects it; the script prints the exact steps.

set -euo pipefail

LOC_HOME="${LOC_HOME:-$HOME/.locutorium}"
FORCE="no"
[[ "${1:-}" == "--force" ]] && { FORCE="yes"; shift; }
[[ $# -ge 1 ]] || { echo "usage: bootstrap.sh [--force] <endpoint> [...]" >&2; exit 1; }
ENDPOINTS=("$@")

if [[ -e "$LOC_HOME/nats-server.conf" && "$FORCE" != "yes" ]]; then
  echo "bootstrap: $LOC_HOME already holds a deployment (use --force to regenerate)" >&2
  exit 1
fi

command -v nats >/dev/null || { echo "bootstrap: nats(1) not found" >&2; exit 1; }

mkdir -p "$LOC_HOME/creds" "$LOC_HOME/store" "$LOC_HOME/hooks"
chmod 700 "$LOC_HOME/creds"

pw_for() { openssl rand -hex 16; }
bcrypt_for() { nats server passwd -p "$1"; }

# --- config + registry -------------------------------------------------------
cat > "$LOC_HOME/config" <<EOF
provider = nats
nats_url = nats://127.0.0.1:4222
topic_window = 7d
EOF
printf '%s\n' "${ENDPOINTS[@]}" > "$LOC_HOME/endpoints"

# --- users -------------------------------------------------------------------
users_block=""
for name in "${ENDPOINTS[@]}" admin watch; do
  pw="$(pw_for)"
  printf '%s' "$pw" > "$LOC_HOME/creds/$name"
  chmod 600 "$LOC_HOME/creds/$name"
  hash="$(bcrypt_for "$pw")"
  case "$name" in
    admin)
      users_block+="      { user: admin, password: \"$hash\" }"$'\n' ;;
    watch)
      users_block+="      { user: watch, password: \"$hash\", permissions: {
          subscribe: { allow: [\"queue.>\", \"topic.>\"] },
          publish:   { deny:  [\">\"] } } }"$'\n' ;;
    *)
      users_block+="      { user: $name, password: \"$hash\", permissions: {
          publish: { allow: [
            \"queue.*\", \"topic.>\",
            \"\$JS.ACK.QUEUE_$name.>\", \"\$JS.ACK.TOPICS.$name.>\",
            \"\$JS.API.INFO\",
            \"\$JS.API.STREAM.INFO.*\", \"\$JS.API.STREAM.NAMES\", \"\$JS.API.STREAM.LIST\",
            \"\$JS.API.STREAM.SUBJECTS.TOPICS\",
            \"\$JS.API.CONSUMER.INFO.>\",
            \"\$JS.API.CONSUMER.MSG.NEXT.QUEUE_$name.$name\",
            \"\$JS.API.CONSUMER.MSG.NEXT.TOPICS.$name\",
            \"\$JS.API.CONSUMER.DURABLE.CREATE.TOPICS.$name\",
            \"\$JS.API.CONSUMER.CREATE.TOPICS.$name\", \"\$JS.API.CONSUMER.CREATE.TOPICS.$name.>\" ] },
          subscribe: { allow: [\"queue.$name\", \"topic.>\", \"_INBOX.>\"] } } }"$'\n' ;;
  esac
done

# --- server config -----------------------------------------------------------
cat > "$LOC_HOME/nats-server.conf" <<EOF
# Locutorium deployment — generated by bootstrap.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Loopback only: this instance is the inner room. Nothing here listens
# beyond the machine.
listen: 127.0.0.1:4222
server_name: locutorium

jetstream {
  store_dir: $LOC_HOME/store
}

authorization {
  users [
$(printf '%s' "$users_block" | sed 's/^/    /')
  ]
}
EOF

echo "deployment written to $LOC_HOME for endpoints: ${ENDPOINTS[*]}"
echo
echo "next steps:"
echo "  1. point your nats-server service at $LOC_HOME/nats-server.conf and start it"
echo "  2. LOC_IDENTITY=admin loc doctor --init     # create streams"
echo "  3. loc doctor                               # verify as a real endpoint"
